from enum import Enum


MAXIMUM_NUMBER_OF_WEBCAMS_ASSUMED = 10
PRESS_THRESHOLD = 40
PIANO_WHITE_KEY = {"WIDTH": 40, "HEIGHT": 200}
PIANO_BLACK_KEY = {"WIDTH": 20, "HEIGHT": 120}
NUMBER_OF_OCTAVES_TO_BE_DRAWN = 2
PRIMARY_COLOR = (64, 54, 251)
PRESSED_KEY_COLOR = PRIMARY_COLOR
AUDIO_RECORDING_SAMPLE_RATE = 48000


class KeyTypeEnum(Enum):
    WHITE_KEY = "WHITE_KEY"
    BLACK_KEY = "BLACK_KEY"


class RabbitMQQueues(Enum):
    VIRTUAL_PIANO = "VIRTUAL_PIANO"
