from enum import Enum


MAXIMUM_NUMBER_OF_WEBCAMS_ASSUMED = 10
PRESS_THRESHOLD = 40
PIANO_WHITE_KEY = {"WIDTH": 40, "HEIGHT": 200}
PIANO_BLACK_KEY = {"WIDTH": 20, "HEIGHT": 120}


class RabbitMQQueues(Enum):
    VIRTUAL_PIANO = "VIRTUAL_PIANO"
